# Generated by Django 5.2.13 on 2026-04-23 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("folders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("study_content", models.TextField(blank=True, null=True)),
                ("file_content", models.TextField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=10, null=True)),
                ("pdf_content", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("progress", models.IntegerField(default=0)),
                ("topics_count", models.IntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="in_progress", max_length=20)),
                ("is_completed", models.BooleanField(default=False)),
                ("has_full_study", models.BooleanField(default=False)),
                ("has_speed_run", models.BooleanField(default=False)),
                ("has_quiz", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="folders.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("is_category", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("current_question_index", models.IntegerField(default=0)),
                ("mentor_narrative", models.TextField(blank=True, null=True)),
                ("workflow_stage", models.CharField(default="locked", max_length=30)),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="study.topic",
                    ),
                ),
                (
                    "study_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="study.studysession",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.IntegerField()),
                ("explanation", models.TextField(blank=True, default="")),
                ("source_text", models.TextField(blank=True, null=True)),
                ("source_page", models.IntegerField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="study.topic",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("hint", models.TextField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("difficulty", models.CharField(default="medium", max_length=20)),
                ("times_reviewed", models.IntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="study.topic",
                    ),
                ),
            ],
            options={
                "db_table": "flashcards",
                "ordering": ["order_index"],
            },
        ),
    ]
